import {
    LayoutDashboard,
    Clock,
    ClipboardList,
    CalendarClock,
    Calendar,
    User,
    MessageSquare,
    Bell,
    Receipt,
    Pill,
    Stethoscope,
    Users,
    FileBarChart,
    ChartBar,
} from "lucide-react";

export const MENU_ITEMS = [
    { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
    { label: "Manage Wait List", href: "/wait-list", icon: Clock },
    { label: "Manage Admission", href: "/admission", icon: ClipboardList },
    { label: "Shift & Assignment", href: "/shifts", icon: CalendarClock },
    { label: "Manage Appointment", href: "/appointments", icon: Calendar },
    { label: "Patient Profile", href: "/patients", icon: User },
    { label: "Chat with patient", href: "/chat-support", icon: MessageSquare },
    { label: "Send Notification", href: "/notifications", icon: Bell },
    { label: "Invoice & Payments", href: "/invoices", icon: Receipt },
    { label: "Drug Catalog", href: "/drugs", icon: Pill },
    {
        label: "Pharmacy Reports",
        href: "/pharmacy-reports",
        icon: FileBarChart,
    },
    { label: "General Reports", href: "/general-reports", icon: ChartBar },
    { label: "Manage Encounter", href: "/encounters", icon: Stethoscope },
    { label: "Staff Profile", href: "/staff", icon: Users },
];
